library(lubridate)
plot4 <- read.csv("household_power_consumption.txt",sep=";")
plot4$DateTime <- strptime(paste(plot4$Date,plot4$Time,sep=" "),format="%d/%m/%Y %H:%M:%S")
plot4 <- subset(plot4,year(plot4$DateTime)==2007&month(plot4$DateTime)==2&day(plot4$DateTime)<=2)
plot4$Sub_metering_1 <- as.numeric(as.character(plot4$Sub_metering_1))
plot4$Sub_metering_2 <- as.numeric(as.character(plot4$Sub_metering_2))
plot4$Global_active_power <- as.numeric(as.character(plot4$Global_active_power))
plot4$Global_reactive_power <- as.numeric(as.character(plot4$Global_reactive_power))
plot4$Voltage <- as.numeric(as.character(plot4$Voltage))
png(filename="plot4.png",width=480,height=480)
par(mfrow=c(2,2))
with(plot4,plot(DateTime,Global_active_power, xlab="", ylab="Global Active Power", type="n"))
with(plot4,lines(DateTime,Global_active_power))
with(plot4,plot(DateTime,Voltage, xlab="datetime", ylab="Voltage", type="n"))
with(plot4,lines(DateTime,Voltage))
with(plot4,plot(DateTime,Sub_metering_1, xlab="", ylab="Energy sub metering", type="n"))
with(plot4,lines(DateTime,Sub_metering_1,col="black"))
with(plot4,lines(DateTime,Sub_metering_2,col="red"))
with(plot4,lines(DateTime,Sub_metering_3,col="blue"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty="solid")
with(plot4,plot(DateTime,Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="n"))
with(plot4,lines(DateTime,Global_reactive_power))
dev.off()