library(lubridate)
plot3 <- read.csv("household_power_consumption.txt",sep=";")
plot3$DateTime <- strptime(paste(plot3$Date,plot3$Time,sep=" "),format="%d/%m/%Y %H:%M:%S")
plot3 <- subset(plot3,year(plot3$DateTime)==2007&month(plot3$DateTime)==2&day(plot3$DateTime)<=2)
plot3$Sub_metering_1 <- as.numeric(as.character(plot3$Sub_metering_1))
plot3$Sub_metering_2 <- as.numeric(as.character(plot3$Sub_metering_2))
png(filename="plot3.png",width=480,height=480)
with(plot3,plot(DateTime,Sub_metering_1, xlab="", ylab="Energy sub metering", type="n"))
with(plot3,lines(DateTime,Sub_metering_1,col="black"))
with(plot3,lines(DateTime,Sub_metering_2,col="red"))
with(plot3,lines(DateTime,Sub_metering_3,col="blue"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty="solid")
dev.off()