library(lubridate)
plot2 <- read.csv("household_power_consumption.txt",sep=";")
plot2$DateTime <- strptime(paste(plot2$Date,plot2$Time,sep=" "),format="%d/%m/%Y %H:%M:%S")
plot2 <- subset(plot2,year(plot2$DateTime)==2007&month(plot2$DateTime)==2&day(plot2$DateTime)<=2)
plot2$Global_active_power <- as.numeric(as.character(plot2$Global_active_power))
png(filename="plot2.png",width=480,height=480)
with(plot2,plot(DateTime,Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", type="n"))
with(plot2,lines(DateTime,Global_active_power))
dev.off()